version: '3.8'

services:
  app:
    build: .
    container_name: rep-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/rep-db
      - SPRING_DATASOURCE_USERNAME=rep-user
      - SPRING_DATASOURCE_PASSWORD=rep-password
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=rep-minio-access-key
      - MINIO_SECRET_KEY=rep-minio-secret-key
    depends_on:
      - postgres
      - minio

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: rep-db
      POSTGRES_USER: rep-user
      POSTGRES_PASSWORD: rep-password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minio-admin
      MINIO_ROOT_PASSWORD: minio-admin-password
    volumes:
      - miniodata:/data

volumes:
  pgdata:
  miniodata:
